### PR TITLE
Fix Missing Service Definitions

### LINKED ISSUE #3: [4.0.0] Missing service definitions
Appears to be an issue with the 4.0.0 release and commit [`f512bfc13d08624c0b98402b5a063f652ecde184`](https://github.com/shapecode/twig-template-event-bundle/compare/3.1.2...f512bfc13d08624c0b98402b5a063f652ecde184) that I was using when initially testing your changes.

### Error Messages

```
> php bin/console cache:warmup
```

> In ContainerBuilder.php line 1032:
>                                                                                
>   You have requested a non-existent service "shapecode_twig_template_event.handler_manager".

After fixing the missing `shapecode_twig_template_event.handler_manager` service definition.

> In DefinitionErrorExceptionPass.php line 54:
>                                                                                
>   Cannot autowire service "Shapecode\Bundle\TwigTemplateEventBundle\Twig\EventExtension": argument "$eventService" of method "__construct()" references interface "Shapecode\Bundle\TwigTemplateEventBundle\Services\EventServiceInterface" but no such service exists. You should maybe alias this interface to the existing "Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService" service. 

After fixing the missing `Shapecode\Bundle\TwigTemplateEventBundle\Services\EventServiceInterface` service alias

> In DefinitionErrorExceptionPass.php line 54:
>                                                                                
>   Cannot autowire service "Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService": argument "$manager" of method "__construct()" references interface "Shapecode\Bundle\TwigTemplateEventBundle\Manager\HandlerManagerInterface" but no such service exists. You should maybe alias this interface to the existing "Shapecode\Bundle\TwigTemplateEventBundle\Manager\HandlerManager" service.

### shapecode_twig_template_event.handler_manager

It looks like you were in the process of refactoring the string based service names in favor of using the FQCN service names, but left in the `shapecode_twig_template_event.handler_manager` in commit [`38906fed5b8996490c3b20d88796737829829d94`](https://github.com/shapecode/twig-template-event-bundle/commit/38906fed5b8996490c3b20d88796737829829d94) which is still referenced by the string name in the [`EventHandlerCompiler`](https://github.com/shapecode/twig-template-event-bundle/blob/4.0.0/src/DependencyInjection/Compiler/EventHandlerCompiler.php#L18).

[*src/Resources/config/services.yml*](https://github.com/shapecode/twig-template-event-bundle/blob/38906fed5b8996490c3b20d88796737829829d94/src/Resources/config/services.yml)
```yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # services
  Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService: ~
  Shapecode\Bundle\TwigTemplateEventBundle\Twig\EventExtension: ~
  Shapecode\Bundle\TwigTemplateEventBundle\Manager\HandlerManager: ~

  # handler
  Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\IncludeHandler:
    tags: ['shapecode_twig_template_event.handler']

  Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\RenderHandler:
    arguments: ["@fragment.handler"]
    tags: ['shapecode_twig_template_event.handler']

  Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\StringHandler:
    tags: ['shapecode_twig_template_event.handler']
```

[*src/DependencyInjection/Compiler/EventHandlerCompiler.php*](https://github.com/shapecode/twig-template-event-bundle/blob/38906fed5b8996490c3b20d88796737829829d94/src/DependencyInjection/Compiler/EventHandlerCompiler.php)
```php
declare(strict_types=1);

namespace Shapecode\Bundle\TwigTemplateEventBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

final class EventHandlerCompiler implements CompilerPassInterface
{
    /**
     * @inheritDoc
     */
    public function process(ContainerBuilder $container): void
    {
        //expected: \Shapecode\Bundle\TwigTemplateEventBundle\Manager\HandlerManager::class
        $manager = $container->getDefinition('shapecode_twig_template_event.handler_manager');
        $tags    = $container->findTaggedServiceIds('shapecode_twig_template_event.handler');

        foreach ($tags as $id => $config) {
            $manager->addMethodCall('addHandler', [new Reference($id)]);
        }
    }
}
```

-----

### Interfaces

Additionally appears that several services are requiring interfaces that are not properly aliased for autowire in the current configuration and are not manually declared.

- **Shapecode\Bundle\TwigTemplateEventBundle\Services\EventServiceInterface**  in [`Shapecode\Bundle\TwigTemplateEventBundle\Twig\EventExtension::__construct()`](https://github.com/shapecode/twig-template-event-bundle/blob/master/src/Twig/EventExtension.php#L17)
- **Shapecode\Bundle\TwigTemplateEventBundle\Manager\HandlerManagerInterface** in [`Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService::__construct()`](https://github.com/shapecode/twig-template-event-bundle/blob/master/src/Services/EventService.php#L29)

### PR DESCRIPTION
**Pull request by fyrye**
Fix #3
Adds aliases of services as root interface for autowire Dependency Injection
Replace `shapecode_twig_template_event.handler_manager` service name string in favor of using FQCN service name

### CODE REVIEW

File: src/DependencyInjection/Compiler/EventHandlerCompiler.php [hunk 1]
```diff
@@ -15,7 +16,7 @@ final class EventHandlerCompiler implements CompilerPassInterface
      */
     public function process(ContainerBuilder $container): void
     {
-        $manager = $container->getDefinition('shapecode_twig_template_event.handler_manager');
+        $manager = $container->getDefinition(HandlerManager::class);
```
Comment (nicklog) [inline src/DependencyInjection/Compiler/EventHandlerCompiler.php]: I would suggest to changed this to "findDefinition" and use the Interface.
```suggestion
        $manager = $container->findDefinition(HandlerManagerInterface::class);
```

**Review by nicklog — COMMENTED** [review]
Hey, thanks for your PR. I just made a simple suggestion. Take a look :)

**Comment by fyrye** [comment]
@nicklog resolved, (not sure if github notifies resolutions without responses). Had to also rename the import to reflect the interface that I missed in the suggestion.

**Comment by nicklog** [comment]
Lets merge it :)
